basePath: /
definitions:
  domain.Record:
    properties:
      audioName:
        type: string
      createdAt:
        type: string
      goodPercent:
        type: integer
      id:
        type: integer
      isOk:
        type: boolean
      text:
        type: string
    type: object
  dto.ConversationRequest:
    properties:
      text:
        type: string
    required:
    - text
    type: object
  response.Body:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
  description: API Server for Hackathon
  title: Hackathon API
  version: "1.0"
paths:
  /conversation/file:
    post:
      consumes:
      - multipart/form-data
      description: Принимает аудиофайл разговора
      operationId: load-conversation-file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Body'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.Body'
      summary: Загрузка аудиофайла разговора
      tags:
      - conversation
  /conversation/file/{name}:
    get:
      description: Получение аудиофайла разговора по его названию. Возвращает файл
      operationId: get-conversation-file
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.Body'
      summary: Получение аудиофайла разговора по его названию
      tags:
      - conversation
  /conversation/file/send_ai/{name}:
    post:
      description: Отправка аудиофайла нейронке
      operationId: send-file-ai
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Body'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.Body'
      summary: Отправка аудиофайла нейронке
      tags:
      - conversation
  /conversation/records:
    get:
      description: Отправка записей
      operationId: get-records
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.Record'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.Body'
      summary: Получение записей
      tags:
      - record
  /conversation/records/{id}:
    get:
      description: Получение записи
      operationId: get-record
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Record'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.Body'
      summary: Получение записи
      tags:
      - record
  /conversation/text:
    post:
      description: Принимает текст разговора
      operationId: load-conversation-text
      parameters:
      - description: текст сообщения
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dto.ConversationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.Body'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Body'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Body'
        default:
          description: ""
          schema:
            $ref: '#/definitions/response.Body'
      summary: Загрузка текста разговора
      tags:
      - conversation
swagger: "2.0"
