// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: pkg/proto/conversation.proto

package conversation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConversationClient is the client API for Conversation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationClient interface {
	AnalyzeAudio(ctx context.Context, opts ...grpc.CallOption) (Conversation_AnalyzeAudioClient, error)
}

type conversationClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationClient(cc grpc.ClientConnInterface) ConversationClient {
	return &conversationClient{cc}
}

func (c *conversationClient) AnalyzeAudio(ctx context.Context, opts ...grpc.CallOption) (Conversation_AnalyzeAudioClient, error) {
	stream, err := c.cc.NewStream(ctx, &Conversation_ServiceDesc.Streams[0], "/conversation.Conversation/AnalyzeAudio", opts...)
	if err != nil {
		return nil, err
	}
	x := &conversationAnalyzeAudioClient{stream}
	return x, nil
}

type Conversation_AnalyzeAudioClient interface {
	Send(*ConversationRequest) error
	Recv() (*ConversationReply, error)
	grpc.ClientStream
}

type conversationAnalyzeAudioClient struct {
	grpc.ClientStream
}

func (x *conversationAnalyzeAudioClient) Send(m *ConversationRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *conversationAnalyzeAudioClient) Recv() (*ConversationReply, error) {
	m := new(ConversationReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConversationServer is the server API for Conversation service.
// All implementations must embed UnimplementedConversationServer
// for forward compatibility
type ConversationServer interface {
	AnalyzeAudio(Conversation_AnalyzeAudioServer) error
	mustEmbedUnimplementedConversationServer()
}

// UnimplementedConversationServer must be embedded to have forward compatible implementations.
type UnimplementedConversationServer struct {
}

func (UnimplementedConversationServer) AnalyzeAudio(Conversation_AnalyzeAudioServer) error {
	return status.Errorf(codes.Unimplemented, "method AnalyzeAudio not implemented")
}
func (UnimplementedConversationServer) mustEmbedUnimplementedConversationServer() {}

// UnsafeConversationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationServer will
// result in compilation errors.
type UnsafeConversationServer interface {
	mustEmbedUnimplementedConversationServer()
}

func RegisterConversationServer(s grpc.ServiceRegistrar, srv ConversationServer) {
	s.RegisterService(&Conversation_ServiceDesc, srv)
}

func _Conversation_AnalyzeAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConversationServer).AnalyzeAudio(&conversationAnalyzeAudioServer{stream})
}

type Conversation_AnalyzeAudioServer interface {
	Send(*ConversationReply) error
	Recv() (*ConversationRequest, error)
	grpc.ServerStream
}

type conversationAnalyzeAudioServer struct {
	grpc.ServerStream
}

func (x *conversationAnalyzeAudioServer) Send(m *ConversationReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *conversationAnalyzeAudioServer) Recv() (*ConversationRequest, error) {
	m := new(ConversationRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Conversation_ServiceDesc is the grpc.ServiceDesc for Conversation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Conversation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conversation.Conversation",
	HandlerType: (*ConversationServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AnalyzeAudio",
			Handler:       _Conversation_AnalyzeAudio_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/conversation.proto",
}
